-- Staff profile fields, company-issued accounts, and user files.
alter table public.admins add column if not exists first_name text not null default '';
alter table public.admins add column if not exists last_name text not null default '';
alter table public.admins add column if not exists job_title text not null default '';
alter table public.admins add column if not exists phone text not null default '';
alter table public.admins add column if not exists mobile text not null default '';
alter table public.admins add column if not exists personal_email text not null default '';
alter table public.admins add column if not exists notes text not null default '';
alter table public.admins add column if not exists photo_url text not null default '';
alter table public.admins add column if not exists street text not null default '';
alter table public.admins add column if not exists street2 text not null default '';
alter table public.admins add column if not exists city text not null default '';
alter table public.admins add column if not exists state text not null default '';
alter table public.admins add column if not exists zip text not null default '';
alter table public.admins add column if not exists country text not null default 'United States';
alter table public.admins add column if not exists updated_at text not null default '';

create table if not exists public.admin_company_accounts (
  id bigint generated by default as identity primary key,
  admin_id bigint not null references public.admins(id) on delete cascade,
  type text not null default 'other',
  label text not null default '',
  username text not null default '',
  secret_enc text not null default '',
  notes text not null default '',
  created_at text not null,
  updated_at text not null
);
create index if not exists idx_admin_company_accounts_admin on public.admin_company_accounts(admin_id);

create table if not exists public.admin_staff_files (
  id bigint generated by default as identity primary key,
  admin_id bigint not null references public.admins(id) on delete cascade,
  name text not null,
  url text not null,
  size bigint not null default 0,
  mime text not null default '',
  created_at text not null
);
create index if not exists idx_admin_staff_files_admin on public.admin_staff_files(admin_id);

alter table public.admin_company_accounts enable row level security;
alter table public.admin_staff_files enable row level security;

drop policy if exists admin_company_accounts_admin_all on public.admin_company_accounts;
create policy admin_company_accounts_admin_all on public.admin_company_accounts
for all using (public.is_spectrum_admin()) with check (public.is_spectrum_admin());

drop policy if exists admin_staff_files_admin_all on public.admin_staff_files;
create policy admin_staff_files_admin_all on public.admin_staff_files
for all using (public.is_spectrum_admin()) with check (public.is_spectrum_admin());

grant select, insert, update, delete on table public.admin_company_accounts to anon, authenticated;
grant select, insert, update, delete on table public.admin_staff_files to anon, authenticated;
grant all on table public.admin_company_accounts to service_role;
grant all on table public.admin_staff_files to service_role;
