-- CRM V3: sequences, deal kind, weighted probability, calculator on deal.
-- Grants match V1/V2 admin access (anon + is_spectrum_admin), not service_role only.

alter table public.company_crm_leads
  add column if not exists kind text not null default 'project';

alter table public.company_crm_deals
  add column if not exists kind text not null default 'project';

alter table public.company_crm_deals
  add column if not exists probability integer not null default -1;

alter table public.company_crm_deals
  add column if not exists calculator_query text not null default '';

alter table public.company_crm_deals
  add column if not exists calculator_summary text not null default '';

alter table public.company_crm_activities
  add column if not exists sequence_id bigint;

alter table public.company_crm_activities
  add column if not exists sequence_step integer not null default 0;

create table if not exists public.company_crm_sequences (
  id bigint generated by default as identity primary key,
  seq_key text not null default '',
  name text not null default '',
  auto_source text not null default '',
  active boolean not null default true,
  steps_json text not null default '[]',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists company_crm_sequences_key_idx on public.company_crm_sequences (seq_key);

alter table public.company_crm_sequences enable row level security;
drop policy if exists company_crm_sequences_admin_all on public.company_crm_sequences;
create policy company_crm_sequences_admin_all on public.company_crm_sequences
  for all using (public.is_spectrum_admin()) with check (public.is_spectrum_admin());

grant select, insert, update, delete on table public.company_crm_sequences to anon, authenticated;
grant all on table public.company_crm_sequences to service_role;
grant usage, select on sequence public.company_crm_sequences_id_seq to anon, authenticated, service_role;

create table if not exists public.company_crm_enrollments (
  id bigint generated by default as identity primary key,
  sequence_id bigint,
  lead_id bigint,
  status text not null default 'active',
  step_index integer not null default 0,
  enrolled_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists company_crm_enrollments_lead_idx on public.company_crm_enrollments (lead_id, status);
create index if not exists company_crm_enrollments_seq_idx on public.company_crm_enrollments (sequence_id);

alter table public.company_crm_enrollments enable row level security;
drop policy if exists company_crm_enrollments_admin_all on public.company_crm_enrollments;
create policy company_crm_enrollments_admin_all on public.company_crm_enrollments
  for all using (public.is_spectrum_admin()) with check (public.is_spectrum_admin());

grant select, insert, update, delete on table public.company_crm_enrollments to anon, authenticated;
grant all on table public.company_crm_enrollments to service_role;
grant usage, select on sequence public.company_crm_enrollments_id_seq to anon, authenticated, service_role;
