-- CRM V2: lead email thread, merge pointer, won/lost reasons, activity assignee.
-- Grants match V1 admin access (anon + is_spectrum_admin), not service_role only.

alter table public.company_crm_leads
  add column if not exists merged_into_id bigint;

alter table public.company_crm_deals
  add column if not exists won_reason text not null default '';

alter table public.company_crm_deals
  add column if not exists lost_reason text not null default '';

alter table public.company_crm_activities
  add column if not exists assigned_to text not null default '';

create table if not exists public.company_crm_messages (
  id bigint generated by default as identity primary key,
  lead_id bigint,
  deal_id bigint,
  activity_id bigint,
  direction text not null default 'in',
  from_email text not null default '',
  to_email text not null default '',
  subject text not null default '',
  body text not null default '',
  source text not null default 'compose',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists company_crm_messages_lead_idx on public.company_crm_messages (lead_id, created_at);

alter table public.company_crm_messages enable row level security;
drop policy if exists company_crm_messages_admin_all on public.company_crm_messages;
create policy company_crm_messages_admin_all on public.company_crm_messages
  for all using (public.is_spectrum_admin()) with check (public.is_spectrum_admin());

grant select, insert, update, delete on table public.company_crm_messages to anon, authenticated;
grant all on table public.company_crm_messages to service_role;
grant usage, select on sequence public.company_crm_messages_id_seq to anon, authenticated, service_role;
