-- Zoom Phone CRM: call/SMS/voicemail/recording log + live incoming screen-pop.
-- Grants match V1–V3 admin access (anon + is_spectrum_admin), not service_role only.

alter table public.company_crm_activities
  add column if not exists zoom_event_key text not null default '';

alter table public.company_crm_activities
  add column if not exists zoom_call_id text not null default '';

alter table public.company_crm_activities
  add column if not exists phone_from text not null default '';

alter table public.company_crm_activities
  add column if not exists phone_to text not null default '';

alter table public.company_crm_activities
  add column if not exists phone_direction text not null default '';

alter table public.company_crm_activities
  add column if not exists duration_sec integer not null default 0;

alter table public.company_crm_activities
  add column if not exists recording_id text not null default '';

alter table public.company_crm_activities
  add column if not exists recording_url text not null default '';

alter table public.company_crm_activities
  add column if not exists voicemail_id text not null default '';

alter table public.company_crm_activities
  add column if not exists media_url text not null default '';

create unique index if not exists company_crm_activities_zoom_event_key_idx
  on public.company_crm_activities (zoom_event_key)
  where zoom_event_key <> '';

create index if not exists company_crm_activities_zoom_call_idx
  on public.company_crm_activities (zoom_call_id)
  where zoom_call_id <> '';

create table if not exists public.company_crm_incoming_calls (
  id bigint generated by default as identity primary key,
  row_key text not null default '',
  zoom_call_id text not null default '',
  staff_zoom_user_id text not null default '',
  status text not null default 'ringing',
  direction text not null default 'inbound',
  from_number text not null default '',
  from_name text not null default '',
  to_number text not null default '',
  staff_name text not null default '',
  staff_email text not null default '',
  lead_id bigint,
  customer_id bigint,
  deal_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists company_crm_incoming_calls_row_key_idx
  on public.company_crm_incoming_calls (row_key);
create index if not exists company_crm_incoming_calls_call_idx
  on public.company_crm_incoming_calls (zoom_call_id, status);

alter table public.company_crm_incoming_calls enable row level security;
drop policy if exists company_crm_incoming_calls_admin_all on public.company_crm_incoming_calls;
create policy company_crm_incoming_calls_admin_all on public.company_crm_incoming_calls
  for all using (public.is_spectrum_admin()) with check (public.is_spectrum_admin());

grant select, insert, update, delete on table public.company_crm_incoming_calls to anon, authenticated;
grant all on table public.company_crm_incoming_calls to service_role;
grant usage, select on sequence public.company_crm_incoming_calls_id_seq to anon, authenticated, service_role;

create table if not exists public.company_crm_zoom_staff (
  zoom_user_id text primary key,
  staff_name text not null default '',
  staff_email text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.company_crm_zoom_staff enable row level security;
drop policy if exists company_crm_zoom_staff_admin_all on public.company_crm_zoom_staff;
create policy company_crm_zoom_staff_admin_all on public.company_crm_zoom_staff
  for all using (public.is_spectrum_admin()) with check (public.is_spectrum_admin());

grant select, insert, update, delete on table public.company_crm_zoom_staff to anon, authenticated;
grant all on table public.company_crm_zoom_staff to service_role;
